image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_IMAGE: konstantinmakarenko/telegram-crm-bot

stages:
  - build
  - push

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:latest .
    - docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$CI_COMMIT_SHA
  only:
    - main

push:
  stage: push
  script:
    - docker push $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
  only:
    - main