version: '3.8'

services:
  telegram-crm-bot:
    image: konstantinmakarenko/telegram-crm-bot:latest
    container_name: telegram_crm_bot
    restart: unless-stopped
    env_file:
      - .env  # <-- переменные из .env попадут в контейнер
    volumes:
      - ./bot-data:/app/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M